### ISSUE TITLE
differences with mattdaly/Fountain.js

### ISSUE THREAD

**Issue by pjebs** [jonnygreenwald/Fountain.ts#7]
I was wondering what the differences are with [mattdaly/Fountain.js](https://github.com/mattdaly/Fountain.js/)?

Is this more robust in terms of interpreting or less error prone?

Thanks

**Comment by jonnygreenwald** [comment]
Appreciate the question and your interest in this repo. I forked [mattdaly/Fountain.js](https://github.com/mattdaly/Fountain.js/) a couple of years ago and essentially added typing as well as refactored a few older common JS styles to take advantage of some of the newer methodologies of ES2016. This was mostly a project meant to familiarize myself with Typescript and get some practice typing an older package, which to my knowledge isn't maintained much any more.

Overall, it is at its core exactly the same. The regex's for tokenizing all mirror Matt's original package. I believe Matt's original package did not fully implement all of Fountain to spec so therefore nor does mine.

> Is this more robust in terms of interpreting or less error prone?

To be honest, my assumption is it is no less error prone than his and I have to assume it is also not much of an improvement over the original either in terms of lexing robustness given it uses the same regex.

After working with this package, I actually decided to begin working on my own screenwriting markdown specification and am in the middle of currently writing the library for it. I hope to eventually implement Fountain as well so that those interested may continue supporting Fountain since I think the concept is still a great one given I'm trying to write a spec of my own.

Anyway, this is just background context mostly as that library is still a ways off, but also to note that I don't have a lot of plans to improve or update this package beyond ensuring its working for those who want to use it and fixing obvious issues they find like #8 .

That being said, I am always open to modifying this library to make it better and am happy to look over any PR or improvement those interested may want to contribute since my own library could benefit from an improved Fountain regex too.

**Comment by pjebs** [comment]
Awesome work!

**Comment by jonnygreenwald** [comment]
Hi @pjebs,

Just letting you know that I've renamed `Fountain.ts` to `fountain-js`. 

You can now find the NPM package at <https://www.npmjs.com/package/fountain-js>.

Install:

```
npm install fountain-js
```

Note the import statement is now different too:

``` javascript
import { Fountain } from 'fountain-js';

let fountain = new Fountain();
```
